[build]
  command = "pnpm run build"
  functions = "./src/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api"
  to = "https://pmekh-ackee.netlify.app/api"
  status = 200

[[redirects]]
  from = "/js/script.js"
  to = "https://pmekh-ackee.netlify.app/tracker.js"
  status = 200

[[redirects]]
  from = "/image/og"
  to = "/.netlify/functions/og-image-redirect"
  status = 200