backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: 'images/uploads'

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
